language: php

before_script:
  - ./composer.phar install --dev --prefer-source --no-interaction

php:
  - 5.5
  - 5.6
  - hhvm

script:
  - ./bin/phpcs --standard=psr2 ./src
  - ./bin/phpmd src/ text phpmd.xml
